// export const fragranceData = [
//   {
//     id: 1,
//     name: "Bleu de Chanel",
//     brand: "Chanel",
//     type: "Eau de Parfum",
//     scentFamily: "Woody Aromatic",
//     notes: ["Grapefruit", "Ginger", "Cedar", "Sandalwood", "Incense"],
//     season: ["Spring", "Fall", "Winter"],
//     occasion: ["Office", "Date", "Evening"],
//     intensity: "Moderate",
//     longevity: "Long-lasting",
//     priceRange: "Premium",
//     description:
//       "A timeless masculine fragrance that balances freshness with depth.",
//     slug: "bleu-de-chanel",
//     image: "/images/bleu-de-chanel.jpg",
//     genderProfile: "Masculine",
//   },
//   {
//     id: 2,
//     name: "Sauvage",
//     brand: "Dior",
//     type: "Eau de Toilette",
//     scentFamily: "Fresh Spicy",
//     notes: ["Bergamot", "Pepper", "Lavender", "Ambroxan"],
//     season: ["Spring", "Summer"],
//     occasion: ["Everyday", "Date", "Evening"],
//     intensity: "Strong",
//     longevity: "Very Long-lasting",
//     priceRange: "Luxury",
//     description: "A raw, fresh fragrance that embodies freedom and adventure.",
//     slug: "dior-sauvage",
//     image: "/images/dior-sauvage.jpg",
//     genderProfile: "Masculine",
//   },
//   {
//     id: 3,
//     name: "Acqua di Gio",
//     brand: "Giorgio Armani",
//     type: "Eau de Toilette",
//     scentFamily: "Aquatic",
//     notes: ["Marine Notes", "Bergamot", "Neroli", "Jasmine", "Patchouli"],
//     season: ["Spring", "Summer"],
//     occasion: ["Everyday", "Office", "Casual"],
//     intensity: "Light",
//     longevity: "Moderate",
//     priceRange: "Premium",
//     description:
//       "A fresh, aquatic fragrance inspired by the Italian island of Pantelleria.",
//     slug: "acqua-di-gio",
//     image: "/images/acqua-di-gio.jpg",
//     genderProfile: "Masculine",
//   },
//   {
//     id: 4,
//     name: "Terre d'Hermès",
//     brand: "Hermès",
//     type: "Eau de Toilette",
//     scentFamily: "Woody Citrus",
//     notes: ["Orange", "Grapefruit", "Flint", "Cedar", "Benzoin"],
//     season: ["Fall", "Winter"],
//     occasion: ["Office", "Evening", "Formal"],
//     intensity: "Moderate",
//     longevity: "Long-lasting",
//     priceRange: "Luxury",
//     description:
//       "An earthy, sophisticated scent that captures the essence of the earth.",
//     slug: "terre-dhermes",
//     image: "/images/terre-dhermes.jpg",
//     genderProfile: "Masculine",
//   },
//   {
//     id: 5,
//     name: "Aventus",
//     brand: "Creed",
//     type: "Eau de Parfum",
//     scentFamily: "Fruity Woody",
//     notes: ["Pineapple", "Black Currant", "Birch", "Musk", "Oakmoss"],
//     season: ["All Year"],
//     occasion: ["Special", "Evening", "Date"],
//     intensity: "Strong",
//     longevity: "Very Long-lasting",
//     priceRange: "Niche",
//     description: "A legendary fragrance symbolizing success and power.",
//     slug: "creed-aventus",
//     image: "/images/creed-aventus.webp",
//     genderProfile: "Masculine",
//   },
//   {
//     id: 6,
//     name: "La Vie Est Belle",
//     brand: "Lancôme",
//     type: "Eau de Parfum",
//     scentFamily: "Gourmand",
//     notes: ["Iris", "Patchouli", "Praline", "Vanilla"],
//     season: ["Fall", "Winter"],
//     occasion: ["Date", "Evening", "Special"],
//     intensity: "Strong",
//     longevity: "Very Long-lasting",
//     priceRange: "Premium",
//     description: "A joyful gourmand fragrance celebrating happiness.",
//     slug: "la-vie-est-belle",
//     image: "/images/la-vie-est-belle.webp",
//     genderProfile: "Feminine",
//   },
//   {
//     id: 7,
//     name: "Black Opium",
//     brand: "Yves Saint Laurent",
//     type: "Eau de Parfum",
//     scentFamily: "Oriental",
//     notes: ["Coffee", "Vanilla", "White Flowers", "Pear"],
//     season: ["Fall", "Winter", "Evening"],
//     occasion: ["Date", "Party", "Evening"],
//     intensity: "Strong",
//     longevity: "Very Long-lasting",
//     priceRange: "Premium",
//     description:
//       "An addictive rock'n'roll fragrance with coffee and vanilla notes.",
//     slug: "black-opium",
//     image: "/images/black-opium.jpg",
//     genderProfile: "Feminine",
//   },
//   {
//     id: 8,
//     name: "Light Blue",
//     brand: "Dolce & Gabbana",
//     type: "Eau de Toilette",
//     scentFamily: "Citrus",
//     notes: ["Sicilian Lemon", "Apple", "Bamboo", "White Rose"],
//     season: ["Spring", "Summer"],
//     occasion: ["Everyday", "Casual", "Daytime"],
//     intensity: "Light",
//     longevity: "Moderate-lasting",
//     priceRange: "Affordable",
//     description: "A fresh, Mediterranean-inspired fragrance for summer days.",
//     slug: "light-blue",
//     image: "/images/light-blue.jpg",
//     genderProfile: "Feminine",
//   },
//   {
//     id: 9,
//     name: "Santal 33",
//     brand: "Le Labo",
//     type: "Eau de Parfum",
//     scentFamily: "Woody",
//     notes: ["Sandalwood", "Violet", "Papyrus", "Cardamom"],
//     season: ["Fall", "Winter"],
//     occasion: ["Office", "Casual", "Evening"],
//     intensity: "Moderate",
//     longevity: "Long-lasting",
//     priceRange: "Niche",
//     description: "A unisex fragrance that has become a modern classic.",
//     slug: "santal-33",
//     image: "/images/santal-33.jpg",
//     genderProfile: "Unisex",
//   },
//   {
//     id: 10,
//     name: "Baccarat Rouge 540",
//     brand: "Maison Francis Kurkdjian",
//     type: "Extrait de Parfum",
//     scentFamily: "Amber Floral",
//     notes: ["Saffron", "Jasmine", "Amberwood", "Cedar"],
//     season: ["All Year"],
//     occasion: ["Special", "Evening", "Date"],
//     intensity: "Strong",
//     longevity: "Very Long-lasting",
//     priceRange: "Luxury",
//     description:
//       "A luxurious, addictive scent that leaves a lasting impression.",
//     slug: "baccarat-rouge-540",
//     image: "/images/baccarat-rouge-540.webp",
//     genderProfile: "Unisex",
//   },
//   {
//     id: 11,
//     name: "Eros",
//     brand: "Versace",
//     type: "Eau de Toilette",
//     scentFamily: "Fresh Oriental",
//     notes: ["Mint", "Green Apple", "Tonka Bean", "Vanilla"],
//     season: ["Fall", "Winter"],
//     occasion: ["Date", "Party", "Evening"],
//     intensity: "Strong",
//     longevity: "Long-lasting",
//     priceRange: "Affordable",
//     description: "A sensual, seductive fragrance inspired by Greek mythology.",
//     slug: "versace-eros",
//     image: "/images/versace-eros.jpg",
//     genderProfile: "Masculine",
//   },
//   {
//     id: 12,
//     name: "One Million",
//     brand: "Paco Rabanne",
//     type: "Eau de Toilette",
//     scentFamily: "Spicy Leather",
//     notes: ["Blood Orange", "Mint", "Cinnamon", "Leather"],
//     season: ["Fall", "Winter"],
//     occasion: ["Party", "Date", "Evening"],
//     intensity: "Strong",
//     longevity: "Long-lasting",
//     priceRange: "Affordable",
//     description: "A bold, attention-grabbing scent for confident individuals.",
//     slug: "one-million",
//     image: "/images/one-million.webp",
//     genderProfile: "Masculine",
//   },
//   {
//     id: 13,
//     name: "Flowerbomb",
//     brand: "Viktor & Rolf",
//     type: "Eau de Parfum",
//     scentFamily: "Floral",
//     notes: ["Tea", "Bergamot", "Jasmine", "Patchouli"],
//     season: ["Spring", "Summer"],
//     occasion: ["Everyday", "Office", "Date"],
//     intensity: "Moderate",
//     longevity: "Long-lasting",
//     priceRange: "Premium",
//     description: "An explosive floral bouquet that's both modern and romantic.",
//     slug: "flowerbomb",
//     image: "/images/flowerbomb.jpg",
//     genderProfile: "Feminine",
//   },
//   {
//     id: 14,
//     name: "Coco Mademoiselle",
//     brand: "Chanel",
//     type: "Eau de Parfum",
//     scentFamily: "Chypre Floral",
//     notes: ["Orange", "Rose", "Patchouli", "Vetiver"],
//     season: ["All Year"],
//     occasion: ["Office", "Date", "Evening"],
//     intensity: "Moderate",
//     longevity: "Long-lasting",
//     priceRange: "Luxury",
//     description:
//       "A modern, sophisticated fragrance for the contemporary woman.",
//     slug: "coco-mademoiselle",
//     image: "/images/coco-mademoiselle.jpg",
//     genderProfile: "Feminine",
//   },
//   {
//     id: 15,
//     name: "The One",
//     brand: "Dolce & Gabbana",
//     type: "Eau de Parfum",
//     scentFamily: "Oriental",
//     notes: ["Bergamot", "Lychee", "Peach", "Vanilla", "Amber"],
//     season: ["Fall", "Winter"],
//     occasion: ["Date", "Evening", "Special"],
//     intensity: "Moderate",
//     longevity: "Moderate-lasting",
//     priceRange: "Premium",
//     description: "A warm, sensual fragrance perfect for intimate evenings.",
//     slug: "the-one",
//     image: "/images/the-one.jpg",
//     genderProfile: "Masculine",
//   },
//   {
//     id: 16,
//     name: "Allure Homme Sport",
//     brand: "Chanel",
//     type: "Eau de Toilette",
//     scentFamily: "Fresh Aromatic",
//     notes: ["Aldehydes", "Neroli", "Cedar", "Tonka Bean"],
//     season: ["Spring", "Summer"],
//     occasion: ["Sport", "Casual", "Everyday"],
//     intensity: "Light",
//     longevity: "Moderate-lasting",
//     priceRange: "Premium",
//     description: "A vibrant, energetic fragrance for the active man.",
//     slug: "allure-homme-sport",
//     image: "/images/allure-homme-sport.jpg",
//     genderProfile: "Masculine",
//   },
//   {
//     id: 17,
//     name: "Angel",
//     brand: "Mugler",
//     type: "Eau de Parfum",
//     scentFamily: "Gourmand",
//     notes: ["Patchouli", "Chocolate", "Caramel", "Honey"],
//     season: ["Fall", "Winter"],
//     occasion: ["Evening", "Special", "Date"],
//     intensity: "Strong",
//     longevity: "Very Long-lasting",
//     priceRange: "Premium",
//     description: "A revolutionary gourmand that changed perfumery forever.",
//     slug: "angel",
//     image: "/images/angel.jpg",
//     genderProfile: "Feminine",
//   },
//   {
//     id: 18,
//     name: "L'Homme",
//     brand: "Yves Saint Laurent",
//     type: "Eau de Toilette",
//     scentFamily: "Fresh Spicy",
//     notes: ["Ginger", "Bergamot", "Violet", "Tonka Bean"],
//     season: ["All Year"],
//     occasion: ["Office", "Everyday", "Casual"],
//     intensity: "Moderate",
//     longevity: "Moderate-lasting",
//     priceRange: "Premium",
//     description: "An elegant, versatile fragrance for the modern gentleman.",
//     slug: "lhomme",
//     image: "/images/lhomme.webp",
//     genderProfile: "Masculine",
//   },
//   {
//     id: 19,
//     name: "Good Girl",
//     brand: "Carolina Herrera",
//     type: "Eau de Parfum",
//     scentFamily: "Oriental Floral",
//     notes: ["Almond", "Coffee", "Tuberose", "Tonka Bean"],
//     season: ["Fall", "Winter"],
//     occasion: ["Evening", "Date", "Special"],
//     intensity: "Strong",
//     longevity: "Long-lasting",
//     priceRange: "Premium",
//     description:
//       "A seductive, dualistic fragrance in an iconic stiletto bottle.",
//     slug: "good-girl",
//     image: "/images/good-girl.jpg",
//     genderProfile: "Feminine",
//   },
//   {
//     id: 20,
//     name: "Spicebomb",
//     brand: "Viktor & Rolf",
//     type: "Eau de Parfum",
//     scentFamily: "Spicy",
//     notes: ["Chili", "Saffron", "Tobacco", "Leather"],
//     season: ["Fall", "Winter"],
//     occasion: ["Evening", "Date", "Special"],
//     intensity: "Strong",
//     longevity: "Long-lasting",
//     priceRange: "Premium",
//     description: "An explosive blend of spices and tobacco notes.",
//     slug: "spicebomb",
//     image: "/images/spicebomb.jpg",
//     genderProfile: "Masculine",
//   },
//   {
//     id: 21,
//     name: "J'adore",
//     brand: "Dior",
//     type: "Eau de Parfum",
//     scentFamily: "Floral",
//     notes: ["Pear", "Magnolia", "Jasmine", "Ylang-Ylang"],
//     season: ["Spring", "Summer"],
//     occasion: ["Office", "Date", "Special"],
//     intensity: "Moderate",
//     longevity: "Long-lasting",
//     priceRange: "Luxury",
//     description: "A golden floral bouquet celebrating divine femininity.",
//     slug: "jadore",
//     image: "/images/jadore.jpg",
//     genderProfile: "Feminine",
//   },
//   {
//     id: 22,
//     name: "Invictus",
//     brand: "Paco Rabanne",
//     type: "Eau de Toilette",
//     scentFamily: "Aquatic",
//     notes: ["Grapefruit", "Marine Notes", "Bay Leaf", "Ambergris"],
//     season: ["Spring", "Summer"],
//     occasion: ["Sport", "Casual", "Everyday"],
//     intensity: "Strong",
//     longevity: "Moderate-lasting",
//     priceRange: "Affordable",
//     description: "A victorious aquatic fragrance for champions.",
//     slug: "invictus",
//     image: "/images/invictus.jpg",
//     genderProfile: "Masculine",
//   },
//   {
//     id: 23,
//     name: "Chance Eau Tendre",
//     brand: "Chanel",
//     type: "Eau de Toilette",
//     scentFamily: "Floral Fruity",
//     notes: ["Grapefruit", "Quince", "Jasmine", "Hyacinth"],
//     season: ["Spring", "Summer"],
//     occasion: ["Everyday", "Casual", "Daytime"],
//     intensity: "Light",
//     longevity: "Moderate-lasting",
//     priceRange: "Luxury",
//     description: "A tender, romantic interpretation of chance encounters.",
//     slug: "chance-eau-tendre",
//     image: "/images/chance-eau-tendre.webp",
//     genderProfile: "Feminine",
//   },
//   {
//     id: 24,
//     name: "Gentleman",
//     brand: "Givenchy",
//     type: "Eau de Parfum",
//     scentFamily: "Woody Oriental",
//     notes: ["Pear", "Vanilla", "Patchouli", "Black Vanilla"],
//     season: ["Fall", "Winter"],
//     occasion: ["Office", "Evening", "Date"],
//     intensity: "Moderate",
//     longevity: "Long-lasting",
//     priceRange: "Premium",
//     description: "A modern gentleman's fragrance with contemporary elegance.",
//     slug: "gentleman",
//     image: "/images/gentleman.jpg",
//     genderProfile: "Masculine",
//   },
//   {
//     id: 25,
//     name: "Idôle",
//     brand: "Lancôme",
//     type: "Eau de Parfum",
//     scentFamily: "Floral",
//     notes: ["Rose", "Jasmine", "Bergamot", "Vanilla"],
//     season: ["All Year"],
//     occasion: ["Office", "Date", "Special"],
//     intensity: "Moderate",
//     longevity: "Long-lasting",
//     priceRange: "Premium",
//     description: "A luminous floral fragrance for the new generation.",
//     slug: "idole",
//     image: "/images/idole.jpg",
//     genderProfile: "Feminine",
//   },
//   {
//     id: 26,
//     name: "Tobacco Vanille",
//     brand: "Tom Ford",
//     type: "Eau de Parfum",
//     scentFamily: "Spicy Gourmand",
//     notes: ["Tobacco Leaf", "Vanilla", "Cacao", "Tonka Bean", "Dried Fruits"],
//     season: ["Fall", "Winter"],
//     occasion: ["Evening", "Date", "Special", "Formal"],
//     intensity: "Strong",
//     longevity: "Very Long-lasting",
//     priceRange: "Luxury",
//     description:
//       "A warm, spicy fragrance with rich tobacco and sweet vanilla notes.",
//     slug: "tobacco-vanille",
//     image: "/images/tobacco-vanille.jpg",
//     genderProfile: "Unisex",
//   },
//   {
//     id: 27,
//     name: "Red Tobacco",
//     brand: "Mancera",
//     type: "Eau de Parfum",
//     scentFamily: "Spicy Oriental",
//     notes: ["Tobacco", "Cinnamon", "Patchouli", "Vanilla", "Amber"],
//     season: ["Fall", "Winter"],
//     occasion: ["Evening", "Date", "Special"],
//     intensity: "Very Strong",
//     longevity: "Very Long-lasting",
//     priceRange: "Niche",
//     description:
//       "An intense, warm tobacco fragrance with spicy and sweet accords.",
//     slug: "red-tobacco",
//     image: "/images/red-tobacco.jpg",
//     genderProfile: "Masculine",
//   },
//   {
//     id: 28,
//     name: "Angel's Share",
//     brand: "Kilian",
//     type: "Eau de Parfum",
//     scentFamily: "Gourmand",
//     notes: ["Cognac", "Cinnamon", "Oak", "Vanilla", "Tonka Bean"],
//     season: ["Fall", "Winter"],
//     occasion: ["Evening", "Date", "Special", "Holiday"],
//     intensity: "Strong",
//     longevity: "Very Long-lasting",
//     priceRange: "Luxury",
//     description:
//       "A warm, boozy fragrance inspired by fine cognac aging in oak barrels.",
//     slug: "angels-share",
//     image: "/images/angels-share.jpg",
//     genderProfile: "Unisex",
//   },
//   {
//     id: 29,
//     name: "By the Fireplace",
//     brand: "Maison Martin Margiela",
//     type: "Eau de Toilette",
//     scentFamily: "Woody Gourmand",
//     notes: ["Cloves", "Orange Blossom", "Chestnut", "Vanilla", "Peru Balsam"],
//     season: ["Fall", "Winter"],
//     occasion: ["Casual", "Evening", "Cozy"],
//     intensity: "Moderate",
//     longevity: "Long-lasting",
//     priceRange: "Premium",
//     description: "The cozy scent of burning wood and roasting chestnuts.",
//     slug: "by-the-fireplace",
//     image: "/images/by-the-fireplace.jpg",
//     genderProfile: "Unisex",
//   },
//   {
//     id: 30,
//     name: "Oud Wood",
//     brand: "Tom Ford",
//     type: "Eau de Parfum",
//     scentFamily: "Woody",
//     notes: ["Oud", "Sandalwood", "Vanilla", "Tonka Bean", "Amber"],
//     season: ["Fall", "Winter"],
//     occasion: ["Evening", "Formal", "Special"],
//     intensity: "Strong",
//     longevity: "Very Long-lasting",
//     priceRange: "Luxury",
//     description: "A rich, sophisticated oud fragrance with warm woody notes.",
//     slug: "oud-wood",
//     image: "/images/oud-wood.jpg",
//     genderProfile: "Unisex",
//   },
//   {
//     id: 31,
//     name: "Black Orchid",
//     brand: "Tom Ford",
//     type: "Eau de Parfum",
//     scentFamily: "Oriental",
//     notes: ["Truffle", "Bergamot", "Floral Notes", "Vanilla", "Patchouli"],
//     season: ["Fall", "Winter", "Evening"],
//     occasion: ["Evening", "Date", "Special"],
//     intensity: "Strong",
//     longevity: "Very Long-lasting",
//     priceRange: "Luxury",
//     description:
//       "A luxurious, sensual fragrance with dark floral and gourmand notes.",
//     slug: "black-orchid",
//     image: "/images/black-orchid.jpg",
//     genderProfile: "Unisex",
//   },
//   {
//     id: 32,
//     name: "Hypnotic Poison",
//     brand: "Dior",
//     type: "Eau de Parfum",
//     scentFamily: "Oriental Vanilla",
//     notes: ["Almond", "Caraway", "Vanilla", "Sandalwood", "Jasmine"],
//     season: ["Fall", "Winter"],
//     occasion: ["Evening", "Date", "Special"],
//     intensity: "Strong",
//     longevity: "Long-lasting",
//     priceRange: "Premium",
//     description: "A sensual, addictive vanilla fragrance with almond accents.",
//     slug: "hypnotic-poison",
//     image: "/images/hypnotic-poison.jpg",
//     genderProfile: "Feminine",
//   },
//   {
//     id: 33,
//     name: "Shalimar",
//     brand: "Guerlain",
//     type: "Eau de Parfum",
//     scentFamily: "Oriental",
//     notes: ["Bergamot", "Iris", "Vanilla", "Leather", "Sandalwood"],
//     season: ["Fall", "Winter"],
//     occasion: ["Evening", "Special", "Formal"],
//     intensity: "Strong",
//     longevity: "Very Long-lasting",
//     priceRange: "Luxury",
//     description: "A timeless oriental classic with vanilla and powdery notes.",
//     slug: "shalimar",
//     image: "/images/shalimar.jpg",
//     genderProfile: "Feminine",
//   },
//   {
//     id: 34,
//     name: "Libre",
//     brand: "Yves Saint Laurent",
//     type: "Eau de Parfum",
//     scentFamily: "Floral Oriental",
//     notes: ["Lavender", "Orange Blossom", "Vanilla", "Tonka Bean"],
//     season: ["Fall", "Winter"],
//     occasion: ["Office", "Evening", "Date"],
//     intensity: "Moderate",
//     longevity: "Long-lasting",
//     priceRange: "Premium",
//     description: "A bold, feminine fragrance blending lavender and vanilla.",
//     slug: "libre",
//     image: "/images/libre.jpg",
//     genderProfile: "Feminine",
//   },
//   {
//     id: 35,
//     name: "Narciso Rodriguez For Her",
//     brand: "Narciso Rodriguez",
//     type: "Eau de Parfum",
//     scentFamily: "Floral Musky",
//     notes: ["Osmanthus", "Amber", "Vanilla", "Vetiver", "Musk"],
//     season: ["Fall", "Winter"],
//     occasion: ["Office", "Date", "Evening"],
//     intensity: "Moderate",
//     longevity: "Long-lasting",
//     priceRange: "Premium",
//     description: "An elegant, musky floral with warm amber and vanilla notes.",
//     slug: "narciso-rodriguez-for-her",
//     image: "/images/narciso-for-her.jpg",
//     genderProfile: "Feminine",
//   },
//   {
//     id: 36,
//     name: "Grand Soir",
//     brand: "Maison Francis Kurkdjian",
//     type: "Eau de Parfum",
//     scentFamily: "Amber",
//     notes: ["Amber", "Vanilla", "Tonka Bean", "Benzoin"],
//     season: ["Fall", "Winter"],
//     occasion: ["Evening", "Special", "Formal"],
//     intensity: "Strong",
//     longevity: "Very Long-lasting",
//     priceRange: "Luxury",
//     description: "A warm, radiant amber fragrance for elegant evenings.",
//     slug: "grand-soir",
//     image: "/images/grand-soir.jpg",
//     genderProfile: "Unisex",
//   },
//   {
//     id: 37,
//     name: "Spicebomb Extreme",
//     brand: "Viktor & Rolf",
//     type: "Eau de Parfum",
//     scentFamily: "Spicy Gourmand",
//     notes: ["Black Pepper", "Vanilla", "Tobacco", "Leather"],
//     season: ["Fall", "Winter"],
//     occasion: ["Evening", "Date", "Special"],
//     intensity: "Very Strong",
//     longevity: "Very Long-lasting",
//     priceRange: "Premium",
//     description:
//       "An intensified version of Spicebomb with added vanilla warmth.",
//     slug: "spicebomb-extreme",
//     image: "/images/spicebomb-extreme.jpg",
//     genderProfile: "Masculine",
//   },
//   {
//     id: 38,
//     name: "Ombré Leather",
//     brand: "Tom Ford",
//     type: "Eau de Parfum",
//     scentFamily: "Leather",
//     notes: ["Leather", "Jasmine", "Patchouli", "Amber", "Moss"],
//     season: ["Fall", "Winter"],
//     occasion: ["Evening", "Date", "Special"],
//     intensity: "Strong",
//     longevity: "Long-lasting",
//     priceRange: "Luxury",
//     description: "A sophisticated leather fragrance with floral undertones.",
//     slug: "ombre-leather",
//     image: "/images/ombre-leather.jpg",
//     genderProfile: "Unisex",
//   },
//   {
//     id: 39,
//     name: "Velvet Rose & Oud",
//     brand: "Jo Malone",
//     type: "Cologne Intense",
//     scentFamily: "Floral Woody",
//     notes: ["Damask Rose", "Oud", "Clove", "Praline"],
//     season: ["Fall", "Winter"],
//     occasion: ["Evening", "Date", "Special"],
//     intensity: "Moderate",
//     longevity: "Long-lasting",
//     priceRange: "Luxury",
//     description: "A luxurious blend of velvety rose and rich oud wood.",
//     slug: "velvet-rose-oud",
//     image: "/images/velvet-rose-oud.jpg",
//     genderProfile: "Unisex",
//   },
//   {
//     id: 40,
//     name: "Scandal Le Parfum",
//     brand: "Jean Paul Gaultier",
//     type: "Eau de Parfum",
//     scentFamily: "Gourmand",
//     notes: ["Honey", "Orange Blossom", "Caramel", "Patchouli"],
//     season: ["Fall", "Winter"],
//     occasion: ["Evening", "Date", "Party"],
//     intensity: "Strong",
//     longevity: "Very Long-lasting",
//     priceRange: "Premium",
//     description: "A sweet, honeyed gourmand with seductive caramel notes.",
//     slug: "scandal-le-parfum",
//     image: "/images/scandal-le-parfum.jpg",
//     genderProfile: "Feminine",
//   },
//   {
//     id: 41,
//     name: "Si Passione",
//     brand: "Giorgio Armani",
//     type: "Eau de Parfum",
//     scentFamily: "Fruity Floral",
//     notes: ["Pear", "Rose", "Vanilla", "Patchouli"],
//     season: ["Fall", "Winter"],
//     occasion: ["Date", "Evening", "Office"],
//     intensity: "Moderate",
//     longevity: "Long-lasting",
//     priceRange: "Premium",
//     description: "A passionate, fruity-floral with warm vanilla base.",
//     slug: "si-passione",
//     image: "/images/si-passione.jpg",
//     genderProfile: "Feminine",
//   },
//   {
//     id: 42,
//     name: "Lost Cherry",
//     brand: "Tom Ford",
//     type: "Eau de Parfum",
//     scentFamily: "Fruity Gourmand",
//     notes: ["Black Cherry", "Bitter Almond", "Tonka Bean", "Vanilla"],
//     season: ["Fall", "Winter"],
//     occasion: ["Evening", "Date", "Special"],
//     intensity: "Strong",
//     longevity: "Long-lasting",
//     priceRange: "Luxury",
//     description: "A decadent cherry fragrance with almond and vanilla notes.",
//     slug: "lost-cherry",
//     image: "/images/lost-cherry.jpg",
//     genderProfile: "Unisex",
//   },
//   {
//     id: 43,
//     name: "Mon Guerlain",
//     brand: "Guerlain",
//     type: "Eau de Parfum",
//     scentFamily: "Oriental Vanilla",
//     notes: ["Lavender", "Jasmine", "Vanilla", "Sandalwood"],
//     season: ["Fall", "Winter"],
//     occasion: ["Office", "Date", "Everyday"],
//     intensity: "Moderate",
//     longevity: "Long-lasting",
//     priceRange: "Premium",
//     description: "A modern classic blending lavender and vanilla beautifully.",
//     slug: "mon-guerlain",
//     image: "/images/mon-guerlain.jpg",
//     genderProfile: "Feminine",
//   },
//   {
//     id: 44,
//     name: "Good Girl Gone Bad",
//     brand: "Kilian",
//     type: "Eau de Parfum",
//     scentFamily: "Floral",
//     notes: ["Osmanthus", "Jasmine", "Tuberose", "Narcissus"],
//     season: ["All Year"],
//     occasion: ["Evening", "Date", "Special"],
//     intensity: "Strong",
//     longevity: "Long-lasting",
//     priceRange: "Luxury",
//     description: "A sensual floral fragrance with addictive white florals.",
//     slug: "good-girl-gone-bad",
//     image: "/images/good-girl-gone-bad.jpg",
//     genderProfile: "Feminine",
//   },
//   {
//     id: 45,
//     name: "La Nuit de L'Homme",
//     brand: "Yves Saint Laurent",
//     type: "Eau de Toilette",
//     scentFamily: "Spicy Woody",
//     notes: ["Cardamom", "Cedar", "Lavender", "Coumarin"],
//     season: ["Fall", "Winter"],
//     occasion: ["Date", "Evening", "Night"],
//     intensity: "Moderate",
//     longevity: "Moderate-lasting",
//     priceRange: "Premium",
//     description: "A seductive, intimate fragrance perfect for night-time wear.",
//     slug: "la-nuit-de-lhomme",
//     image: "/images/la-nuit-de-lhomme.jpg",
//     genderProfile: "Masculine",
//   },
//   {
//     id: 46,
//     name: "Dolce Amalfi",
//     brand: "Xerjoff",
//     type: "Eau de Parfum",
//     scentFamily: "Fruity Spicy",
//     notes: ["Quince", "Cardamom", "Amber", "Musk"],
//     season: ["Fall", "Winter"],
//     occasion: ["Evening", "Date", "Special"],
//     intensity: "Moderate",
//     longevity: "Long-lasting",
//     priceRange: "Niche",
//     description: "A luxurious fruity-spicy fragrance with warm amber base.",
//     slug: "dolce-amalfi",
//     image: "/images/dolce-amalfi.jpg",
//     genderProfile: "Unisex",
//   },
//   {
//     id: 47,
//     name: "Baccarat Rouge 540 Extrait",
//     brand: "Maison Francis Kurkdjian",
//     type: "Extrait de Parfum",
//     scentFamily: "Amber Floral",
//     notes: ["Saffron", "Jasmine", "Amberwood", "Bitter Almond"],
//     season: ["All Year"],
//     occasion: ["Special", "Evening", "Date"],
//     intensity: "Very Strong",
//     longevity: "Extremely Long-lasting",
//     priceRange: "Luxury",
//     description: "The intense version of the iconic Baccarat Rouge 540.",
//     slug: "baccarat-rouge-540-extrait",
//     image: "/images/baccarat-rouge-540-extrait.jpg",
//     genderProfile: "Unisex",
//   },
//   {
//     id: 48,
//     name: "Olympea",
//     brand: "Paco Rabanne",
//     type: "Eau de Parfum",
//     scentFamily: "Oriental Vanilla",
//     notes: ["Green Mandarin", "Vanilla", "Salt", "Amber"],
//     season: ["Fall", "Winter"],
//     occasion: ["Evening", "Date", "Party"],
//     intensity: "Strong",
//     longevity: "Long-lasting",
//     priceRange: "Premium",
//     description: "A sensual vanilla fragrance with salty, marine accents.",
//     slug: "olympea",
//     image: "/images/olympea.jpg",
//     genderProfile: "Feminine",
//   },
//   {
//     id: 49,
//     name: "My Way",
//     brand: "Giorgio Armani",
//     type: "Eau de Parfum",
//     scentFamily: "Floral",
//     notes: ["Bergamot", "Orange Blossom", "Tuberose", "Vanilla"],
//     season: ["All Year"],
//     occasion: ["Office", "Date", "Everyday"],
//     intensity: "Moderate",
//     longevity: "Long-lasting",
//     priceRange: "Premium",
//     description: "An intense floral with vanilla base notes for warmth.",
//     slug: "my-way",
//     image: "/images/my-way.jpg",
//     genderProfile: "Feminine",
//   },
//   {
//     id: 50,
//     name: "Gentle Fluidity Gold",
//     brand: "Maison Francis Kurkdjian",
//     type: "Eau de Parfum",
//     scentFamily: "Oriental Vanilla",
//     notes: ["Juniper", "Nutmeg", "Vanilla", "Musks"],
//     season: ["Fall", "Winter"],
//     occasion: ["Evening", "Special", "Date"],
//     intensity: "Moderate",
//     longevity: "Long-lasting",
//     priceRange: "Luxury",
//     description: "A warm, vanillic fragrance with spicy and musky notes.",
//     slug: "gentle-fluidity-gold",
//     image: "/images/gentle-fluidity-gold.jpg",
//     genderProfile: "Unisex",
//   },
// ];
